[package]
name = "sudoku"
version = "0.1.0"
authors = ["Ray Tran <rt@elixirsoftware.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
pretty_assertions = "^0.7.2"
